### ISSUE TITLE
[Bug] Không thể add sản phẩm mà không có hình ảnh thứ 4

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#10]
Có thể liên quan đến #8 
Xem kĩ các phần valid này lại nhé.

**Comment by Nadreasky** [comment]
có muốn bỏ luôn cái ô nhập hình số 4 ko, vì đề mà ko nhập thấy sẽ làm user nó cấn :|

**Comment by tuanan94** [comment]
uhm bỏ đi
