### ISSUE TITLE
Chọn sai class của div

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/YourWebsite#11]
Theo như demo của template gốc thì chỉ có phần product nằm kế bên cái slider hiện trend product là chọn span9, còn lại là span12.

T inspect trên web thì toàn bộ là span9 hết, ko biết là m chủ động sửa hay sửa nhầm. Mà sao có cái == $0 kế bên mấy cái div vậy ko biết

![image](https://cloud.githubusercontent.com/assets/15942198/14579077/e6241fce-03c6-11e6-9c15-b68a4168dc44.png)

**Comment by tuanan94** [comment]
Cái đó là do t chủ động nha Quy. span 9 bên trái, span 3 bên phải. Sau này có thể t sẽ sắp trend dọc xuống. Thay vì gom vào 1 cái slider thế này. Nếu clear rồi thì close nhé

**Comment by tuanan94** [comment]
sẳn nhắc ở đây luôn. T có up lên file script đó. Lấy cái đó làm data demo cho dễ test. Hình thì có trong source rồi. Chạy lại cái DB là xong

**Comment by Nadreasky** [comment]
okay
