### ISSUE TITLE
Thiết kế lại quy trình giao hàng 

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#14]
Task này yêu cầu Thy làm lại Quy trình giao hàng rồi để vào vị trị bên dưới các sản phẩm (như trang demo). Hiện tại thì vẫn để ở phía trên, nhìn không được cân đối

**Comment by Nadreasky** [comment]
chờ con thy mần xong òi thay

**Comment by Nadreasky** [comment]
chờ thg D approve

**Comment by tuanan94** [comment]
Cái quy trình giao hàng này mình sẽ dùng cả 2. 
Cái thứ 2 ok rồi nhưng vẫn giữ lại cái thứ nhất, khi nào chán thì thay
