### ISSUE TITLE
Thay đổi SP Bán chạy thành SP có sẳn (Có bao gồm giá )

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#15]

**Comment by Nadreasky** [comment]
-nếu thêm giá như vậy thì nó nhìn ko đều khi so với cái "sản phẩm mới" kế bên
-Tiêu chí để biết sản phẩm đó bán chạy là ntn

**Comment by tuanan94** [comment]
Nó ko phải là bán chạy mà là sản phẩm có sẳn. Là 1 dạng category thôi. Nhưng vị trí của nó là thay cho sản phẩm bán chạy bây giờ

Sent from my iPhone

On Apr 26, 2016, at 6:40 PM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

-nếu thêm giá như vậy thì nó nhìn ko đều khi so với cái "sản phẩm mới" kế bên
-Tiêu chí để biết sản phẩm đó bán chạy là ntn
