### ISSUE TITLE
Logo bên góc phải. Bao gồm ô tìm kiếm (như trang demo)

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#17]

**Comment by Nadreasky** [comment]
demo logo góc trái, thanh tìm kiếm bên fải mà ;|

**Comment by tuanan94** [comment]
Nó là cụm icon chạy chạy bên góc phải. Nếu vẫn chưa thấy tối t về sẽ chụp hình cho dễ hiểu

Sent from my iPhone

On Apr 26, 2016, at 5:55 PM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

demo logo góc trái, thanh tìm kiếm bên fải mà ;|

**Comment by Nadreasky** [comment]
oh sh!t, hỉu òi, bỏ đã h làm lại ==

có lấy lun cái cart hok hay bỏ, cái cart fía header nữa, để đẹp thoy chớ xài au
