### ISSUE TITLE
Làm lại menu 

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#20]
1.Đồng phục công sở
. Vest
. Sơ mi
. Áo thun cổ tròn
. Áo thun có cổ
2.Quà tặng sự kiện
. Áo thun cổ tròn
. Áo thun cổ trụ
. Khác
3.Các kiểu vải và In
. In thông thường
. In cao cấp
. Vải
4.Thông số size
5.Blog
6.Liên hệ và báo giá
7.Giới thiệu
8.Tuyển dụng

**Comment by Nadreasky** [comment]
mấy cái cate số 4 5 6 7 8 thì fải làm trang riêng cho nó hả

**Comment by Nadreasky** [comment]
nó bị nahỷ xuống vài để y nguyên hay chỉnh lại vại
![image](https://cloud.githubusercontent.com/assets/15942198/14816757/e790f094-0bdc-11e6-9d7f-48ee7fd51e9d.png)

**Comment by tuanan94** [comment]
Script lại DB cho ticket này luôn nha. Để đồng bộ menu luôn

Sent from my iPhone

On Apr 27, 2016, at 2:29 PM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #20https://github.com/Nadreasky/YourWebsite/issues/20 via 608c624https://github.com/Nadreasky/YourWebsite/commit/608c62401ac5f566bf5ef91ee1ebd2eb3d266822.

**Comment by Nadreasky** [comment]
thêm vô cái j` mà script lại thía, thông số size hả ??

**Comment by tuanan94** [comment]
Menu. Category lưu trong db

Sent from my iPhone

On Apr 27, 2016, at 6:27 PM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

thêm vô cái j` mà script lại thía, thông số size hả ??

**Comment by Nadreasky** [comment]
là sao chưa hỉu men, cho 200đ detail đi

**Comment by tuanan94** [comment]
Làm sao để quản lí sản phầm có sẳn???

**Comment by Nadreasky** [comment]
zị cứ cho nó là 1 sản phẩm bt, trong db thêm vô 1 field là available, nếu stick thì nó là có sẵn đc hok?

**Comment by tuanan94** [comment]
Thôi t hiểu ý m rồi. Tạo 1 category tên là sp có sẳn đúng ko. Đó là lí do hổm t kêu m script cái db ra đó

Sent from my iPhone

On May 4, 2016, at 9:13 AM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

zị cứ cho nó là 1 sản phẩm bt, trong db thêm vô 1 field là available, nếu stick thì nó là có sẵn đc hok?

**Comment by Nadreasky** [comment]
hok, ko tạo cái cate sp có sẵn cũng đc, cứ để bt rồi trong table product thêm field available, tại sản phẩm có sẵn là nó đã thuộc 1 cate nào đó gồi, h tạo cate 'sp có sẵn' nữa thì hơi thừa, còn ý m muốn ntn nói nghe

**Comment by tuanan94** [comment]
Ko được đâu. Làm theo cách cũ đi. Vì sản phẩm có sẵn là 1 category cùng cấp với những danh mục khác. Ko phải là sp có sẵn của một category khác. Hiểu ko?

Sent from my iPhone

On May 4, 2016, at 10:50 AM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

hok, ko tạo cái cate sp có sẵn cũng đc, cứ để bt rồi trong table product thêm field available, để cần thì lấy ra, còn ý m muốn ntn nói nghe

**Comment by Nadreasky** [comment]
ok, vại thì t làm xong bữa h òi có j` thay đổi đâu mà script db, nếu nó là 1 cate thì có quản lí cate đồ hết òi, add vô như bt thoy mà

**Comment by tuanan94** [comment]
Ok. Bởi vì hôm qua t ko biết phải add cái tên gì vô cho cate sp có sẵn. Nên phải đọc code lại. Nếu co db thì đỡ mất tgian

Sent from my iPhone

On May 4, 2016, at 12:54 PM, Nadreasky <notifications@github.com<mailto:notifications@github.com>> wrote:

ok, vại thì t làm xong bữa h òi có j` thay đổi đâu mà script db, nếu nó là 1 cate thì có quản lí cate đồ hết òi, add vô như bt thoy mà

**Comment by Nadreasky** [comment]
lúc mà add thì chọn trong drop down list ý mà, trong SLIMCONFIG có 1 biến về nó
