### ISSUE TITLE
Update tình hình cho chú

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/YourWebsite#36]
TRANG CHỦ:
1. Mẫu mới đâu phải là mẫu thời trang nhóm hả em? DŨNG CONFIRM GIÚP
==> Này bây tư lo 😄 
1. Sản phẩm có sẵn sao không có hình ảnh vậy? DŨNG CONFIRM GIÚP
   ==> này m add đi nha
2. Quà tặng sự kiện sao không có: túi, áo mua....? 
   ==> Này m add nha
3. Cảm nhận từ khách hàng anh muốn các chữ cùng kích cỡ và nằm trên 1 dòng luôn
   ==> Này t fix rồi
4. Ngăn cân bằng làm 2 cảm nhận của khách hàng & khách hàng của chúng tôi
   ==> ko hiểu ổng nói cái j` @@!
5. Tại sao vẫn chưa thấy logo khách hàng?
   ==> M send t để add vô nha
6. Bottom: thay dia chi, web, dien thoai, email = icon và nhớ cân bằng
   ==> thay = icon gòi, mà ổng kiu cân = là sao? Như vầy đc hok
   ![image](https://cloud.githubusercontent.com/assets/15942198/16481233/546e75b8-3ed4-11e6-8ea1-04ba87408d62.png)

TRANG GIỚI THIỆU
1. Anh có attached file mẫu, chứ anh không muốn đơn điệu như cái của mình. 
2. Hình ảnh thì có thể lấy từ thiết kế vì trong brochure mình có tấm hình văn phòng đó
==> Hai mục trên thì send hình vô t add là ok
1. Cái nào là tầm nhìn? Cái nào là sứ mệnh? em để như vậy người ta sẽ không biết
   ==> Ok thix tách thì tách

TRANG ĐỒNG PHỤC CÔNG SỞ
QUÀ TẶNG SỰ KIỆN
CÁC KIỂU VẢI VÀ ÌN
Anh không muốn có gạch bên dưới, Tuấn An bỏ nó đi , anh có attach hình
Và cũng muốn mình có content vào
==> T bỏ cái gạch òi, còn content thì nó liên wan tới hàm get sản phẩm, dể t sửa hàm get lại ---UPDATE (16:45): sửa xong òi nha

TRANG TIN TỨC

Anh muốn cái bo của các tin là màu xám chứ không phải màu đỏ nhe em
==> T fix gòi

**Comment by tuanan94** [comment]
Trả lời người đẹp từng cái nhé
1. Ngăn cân bằng làm 2 cảm nhận của khách hàng & khách hàng của chúng tôi
   => làm cho 2 phần cảm nhận khách hàng và khách hàng chúng tôi bằng nhau đó
2. Bottom: thay dia chi, web, dien thoai, email = icon và nhớ cân bằng
   Thêm vô icon cho cái địa chỉ nữa. Cân bằng vậy ok rồi
3. Hình ảnh cho trang giới thiệu: xem trong catalog có hình nào ko Quy? Nếu có thì nói Thy gửi hình gốc. Ko thì nói t đòi hình cho.

Xong hôm nay up lên host để t report nha Quy. 

Note: T đang soạn plan cho project web bán lẻ. Xong cái này chắc mình chiến típ dđó
