### ISSUE TITLE
[Bug]Khi edit mà không up ảnh mới thì báo lỗi

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#8]
Reproduce:
Step 1: Edit 1 product
Step 2: Save lại
Actual: HIện thông báo lỗi
Expect: Không hiện thông báo lỗi

**Comment by Nadreasky** [comment]
H có solutions như vầy
1. Bỏ valid là có hình hay ko, lúc create hay edit thì user mún add hay ko add hình đều đc. Sở dĩ như vậy vì fòng hờ trường hợp lúc add mới product user ko có hình hoặc hình ko đủ như yêu cầu (tối thiểu là 3). Còn nếu business bảo đảm lúc add new product chắc chắn có **đủ** hình thì sẽ qua phương án 2
2. Lúc edit check xem đã có hình trong db chưa, nếu có rồi thì ko nhập hình sẽ ko báo lỗi

**Comment by tuanan94** [comment]
Business: sản phẩm có ít nhất 1 product. Nhiều nhất là 3. 
Khi update: Click edit -> Hiển thị hình ảnh (nếu đã có) dưới ô select image. Nếu người dùng giữ nguyên thì ko thay đổi.

**Comment by Nadreasky** [comment]
bên fía table bên fải có thumbnail của từng hình của sp òi, nên bỏ cái vụ lúc click edit hiện lên hình nữa nha, update thêm cái số bên cạnh cái hình bên table bên fải để user biết thôi. Giống như vầy
![image](https://cloud.githubusercontent.com/assets/15942198/14579420/b0ec9f6e-03d2-11e6-8099-0ad55f3f69a6.png)
chỗ edit cũng có số lun
![image](https://cloud.githubusercontent.com/assets/15942198/14579421/d934cec4-03d2-11e6-85af-58776b6c8f1e.png)

Chớ hiện hình nữa nhìn cái khu edit nó dài wá, rối rắm nữa
