### ISSUE TITLE
[Bug] Nếu product của một category dưới 4 thì ở trang chủ có lỗi

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/YourWebsite#9]
Step to reproduce:
1: Chuẩn bị 1 category mà có số product <4
2: Bấm vào nút mũi tên next - previous trên trang chủ - có lỗi product chạy qua phải

Suggest: Vì nó vẫn đúng trên category mà có số product >4. Nên detect nếu < 4 thì không hiện 2 cái nút đó

**Comment by Nadreasky** [comment]
2 cái nút đó là nó tự gen do lúc khi chọn class span vd như
![image](https://cloud.githubusercontent.com/assets/15942198/14579048/31ae2d8c-03c6-11e6-91f8-8cf391e5c2c7.png)
ko có can thiệp để mà chỉnh đc
